theme: jekyll-theme-cayman
title: Learn Italian Today
description: SML209-18
github:
  page2: language.html
  page3: vocabulary.html
  page4: culture.html
  page5: extras.html
  page6: practice.html
  page7: listening_exercise.html
  page8: dialogcards.html
